binning:
  binsperdec: 30
  binsz: 0.2
  roiwidth: 10.0
data:
  evfile: events.lst
  ltcube: /nfs/astrop/n1/kuhlmann/NGC_1275/ts_limit/grid_ts/h1_sim/fits/ltcube_00.fits
fileio:
  logfile: /nfs/astrop/n1/kuhlmann/NGC_1275/ts_limit/grid_ts/h1_sim/fits/fermipy.log
  outdir: /nfs/astrop/n1/kuhlmann/NGC_1275/ts_limit/grid_ts/h1_sim/fits
  workdir: /nfs/astrop/n1/kuhlmann/NGC_1275/ts_limit/grid_ts/h1_sim/fits
gtlike:
  edisp: true
  edisp_bins: -6
  edisp_disable:
  - isodiff
  irfs: P8R3_SOURCE_V3
logging:
  verbosity: 4
model:
  catalogs:
  - gll_psc_v21.xml
  galdiff: /nfs/astrop/n1/kuhlmann/miniconda/envs/fermi3/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits
  isodiff: /nfs/astrop/n1/kuhlmann/miniconda/envs/fermi3/share/fermitools/refdata/fermi/galdiffuse/iso_P8R3_SOURCE_V3_v1.txt
  src_radius: 15.0
selection:
  emax: 500000
  emin: 100
  evclass: 128
  evtype: 3
  filter: DATA_QUAL>0 && LAT_CONFIG==1
  target: 4FGL J0319.8+4130
  tmax: 621322123
  tmin: 239557417
  zmax: 90
